{
  try {
    this.destroy();
  }
 catch (  Exception ex) {
    log.error(ex);
  }
}
