{
  Order existing=service.getOrder(1);
  existing.setOrderNumber("New Number");
  try {
    service.saveOrder(existing);
    Assert.fail("the previous line should have thrown an exception");
  }
 catch (  APIException ex) {
    Assert.assertTrue(ex.getMessage().contains("orderNumber"));
  }
}
