{
  try {
    thread.join();
  }
 catch (  InterruptedException e) {
    log.error("Error generated",e);
  }
}
